"""Add weight_per_meter column to stocks table

Revision ID: 4fb86f7365ee
Revises: 73e188c3df01
Create Date: 2025-03-10 00:49:50.559303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb86f7365ee'
down_revision = '73e188c3df01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_per_meter', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('weight_per_meter')

    # ### end Alembic commands ###
